mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path



from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
)

mysite/polls/urls.py
from django.urls import path


from . import views
app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


from django.db import models

# Create your models here.

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'


    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Nie wybrałeś odpowiedzi.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    if question_id <= 13:
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id+1,)))

    if question_id > 13:
        return render(request, "polls/end.html")

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

<link rel="stylesheet" type="text/css" href="polls/quest.css">
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id}}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Dalej">
</form>

mysite/polls/templates/polls/end.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/end.css' %}">
{% if latest_question_list %}

        <DIV ALIGN="CENTER"><p><b><FONT SIZE=7">ANKIETA</FONT></b></p>
                    <p><i><FONT SIZE="5">Dziękujemy za udział w ankiecie</FONT></i></p>

    </ul></DIV>
{% else %}
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>

    <DIV ALIGN="CENTER"><p><b><FONT SIZE="10">ANKIETA</FONT></b></p>
        <p><i><FONT SIZE="8">Dziękujemy za udział w ankiecie</FONT></i></p></DIV>
{% endif %}

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}

        <DIV ALIGN="CENTER"><p><b><FONT SIZE="7">ANKIETA</FONT></b></p>
                    <p><i><FONT SIZE="5">Zapraszamy do udziału w ankiecie "Zagrożenie udarem mózgu"</FONT></i></p>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul></DIV>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>


<a href="{% url 'polls:detail' question.id %}">Nastepne</a>